Add Error event in Blazor ViewModel (#3279)
MarimerLLC/csla pull request #3915
Opened 2024-05-05 15:14 UTC by rrrooommmaaa

Close #3279

2024-05-05 18:49 UTC, rrrooommmaaa commented on Source/Csla.Blazor.Test/ViewModelSaveAsyncErrorTests.cs
> +      Assert.AreEqual("Inserted", TestResults.GetResult("FakePerson"));
There is problem using `TestResults` for this test. It's probably due to multiple `ConfigureAwait(false)` that `AsyncLocal` is sometimes addressed from different execution contexts.
I'd wire a dedicated variable in the test and a handler to update variable.
Thoughts?

2024-05-05 22:06 UTC, rockfordlhotka requested changes

2024-05-06 07:33 UTC, rrrooommmaaa commented on Source/Csla.Blazor/ViewModel.cs
> +          Error?.Invoke();
Fixed

2024-05-06 08:30 UTC, rockfordlhotka approved these changes

2024-05-06 08:31 UTC, rockfordlhotka commented
@rrrooommmaaa thank you for the updates to the PR. We do still need your contributor agreement.

https://github.com/MarimerLLC/csla/blob/main/CONTRIBUTING.md

2024-05-06 13:06 UTC, rrrooommmaaa commented
> https://github.com/MarimerLLC/csla/blob/main/CONTRIBUTING.md

I have just sent it to you via e-mail.

2024-05-06 14:21 UTC, merged