Added Priority in Broken Rule
MarimerLLC/csla pull request #3945
Opened 2024-05-16 12:25 UTC by Freelancingonupwork

-Updated  'GetFirstBrokenRules()' in BrokenRulesCollection, this method will return 'first' broken rules for the object (or object graph).
-Added Priority to `BrokenRule.cs`

Fixes #3224

2024-05-18 19:53 UTC, StefanOssendorf requested changes

2024-05-18 19:53 UTC, StefanOssendorf commented on Source/Csla/Rules/BrokenRule.cs
> +
Why empty lines here when all other fields are below each other?

2024-05-18 19:53 UTC, StefanOssendorf commented on Source/Csla/Rules/BrokenRule.cs
> +
Why empty lines when all other code is below each other?

2024-05-18 19:53 UTC, StefanOssendorf commented on Source/Csla/Rules/BrokenRule.cs
> +
Remove empty line

2024-05-18 19:53 UTC, StefanOssendorf commented on Source/Csla/Rules/BrokenRulesCollection.cs
> +    internal void SetBrokenRules(List<RuleResult> results, string originPropertyName, int Priority)
Parameters have to be camelCase. So it must be priority not Priority.

2024-05-18 19:53 UTC, StefanOssendorf commented on Source/Csla/Rules/BrokenRulesCollection.cs
> +
Why empty lines here? (Like the others)

2024-05-20 18:08 UTC, StefanOssendorf approved these changes
@rockfordlhotka The changes are okay for me. But please double check if it's what was intended with the associated issue. Thanks

2024-05-20 18:45 UTC, rockfordlhotka requested changes

2024-05-20 18:45 UTC, rockfordlhotka commented on Source/Csla/Rules/BrokenRulesCollection.cs
> +      return this.OrderBy(c => c.Property).FirstOrDefault(c => c.Property == property && c.Severity == severity);
Shouldn't the `OrderBy` be by priority, not property?

2024-05-20 18:46 UTC, rockfordlhotka commented
I added the BreakingChange tag to the original issue, as this does change the behavior of existing methods. Beyond my one request for a potential code change, I like the changes being made here.

2024-05-22 06:27 UTC, Freelancingonupwork commented
> I added the BreakingChange tag to the original issue, as this does change the behavior of existing methods. Beyond my one request for a potential code change, I like the changes being made here.

Is this any changes required here? If not Can you please merge this PR?

2024-05-22 06:33 UTC, Freelancingonupwork commented
Is this any changes required here? If not Can you please merge this PR?

2024-05-22 18:41 UTC, StefanOssendorf commented
@rockfordlhotka Please approv so lgtm :)

2024-05-23 01:12 UTC, rockfordlhotka approved these changes

2024-05-23 01:12 UTC, merged