use expression based properties
MarimerLLC/csla pull request #3947
Opened 2024-05-17 10:00 UTC by SimonCropp

2024-05-18 19:20 UTC, StefanOssendorf requested changes
I'm in general okay with this change. Last decision lies by @rockfordlhotka 

@SimonCropp Could you also please add this change to the editorconfig so it'll b suggested by VS automatically? Thanks

2024-05-18 19:20 UTC, StefanOssendorf commented on Source/Csla.test/MethodCaller/PropertyTests.cs
> +    public string Test2 { get => "two";
Put get on it's own line.

2024-05-18 19:20 UTC, StefanOssendorf commented on Source/Csla.test/ValidationRules/ValidationTests.cs
> +      //if (!FieldManager.FieldExists(Value1Property))
This is now confusing with the change. This belongs to the `get` but reads without knowledge as it belongs to the `set`. So just delete it.

2024-05-20 11:04 UTC, SimonCropp commented
> Could you also please add this change to the editorconfig so it'll b suggested by VS automatically

done

2024-05-20 16:13 UTC, rockfordlhotka approved these changes

2024-05-20 16:14 UTC, rockfordlhotka commented
@StefanOssendorf I'm good with this change - I like the language feature. Once your change request is satisfied it can be merged.

2024-05-20 18:09 UTC, StefanOssendorf commented
@SimonCropp Please fix the conflicts

2024-06-01 18:47 UTC, rockfordlhotka commented
Hi @SimonCropp 

Do you plan to continue working on this PR - to resolve the conflicts - or should I close it without merging?

2024-06-02 09:11 UTC, SimonCropp commented
with that number of conflicts, it is prob easier to close this and resubmit

2024-06-02 09:11 UTC, closed without merging