Feature/asynchronous authorization rules
MarimerLLC/csla pull request #3956
Opened 2024-05-19 19:25 UTC by luizfbicalho

I just added the basic idea so we could talk about the whole spec. 
Didn't add the tests because of that

#2801

2024-05-21 23:17 UTC, luizfbicalho commented
> @luizbicalhoagl, I don't have any immediate concerns about the changes, as long as everything still works 😄
> 
> And by "works" what I mean is that pages that use the API synchronously today keep working, as do any consumers using the API in an async manner.

Thanks for the feedback 

I did my best to create the async methods without impacting on the previous ones

If it's ok for you I can create the tests for some async authorization rules.
Do you have any scenario in mind that needs attention?

@StefanOssendorf do you have something to add?

2024-05-22 02:00 UTC, rockfordlhotka commented
The original request came from @mtavares628, so perhaps he has a good example for testing?

I think the real scenario is an authn rule that needs to do some async data portal command - like read from a database or other backend service. You can simulate this by creating a rule that does a `FetchAsync` on the data portal - perhaps on the logical server-side `Fetch` operation do an `await Task.Delay(10)` or something.

2024-05-22 14:36 UTC, mtavares628 commented
@luizfbicalho, @rockfordlhotka hit the nail on the head with my use case.  I want to create an authorization rule that is able to perform a FetchAsync or ExecuteAsync to retrieve a value back from the database to determine whether the user is authorized or not. The criteria for that fetch would be passed in to the HasPermissionAsync method as the criteria object.  You could probably extend the tests from [PR #1226](https://github.com/MarimerLLC/csla/pull/1226/files) to simulate the fetch. While it just checks the type of the criteria object in those tests, you could instead use the value from the criteria to perform the fetch.

2024-06-01 18:45 UTC, rockfordlhotka commented
@luizfbicalho let me know when you have added tests for this

2024-06-01 18:48 UTC, luizfbicalho commented
> @luizfbicalho let me know when you have added tests for this

I'll finish them thiis week

2024-06-05 01:24 UTC, luizfbicalho commented
> @luizfbicalho let me know when you have added tests for this


I added the tests in a way that I'm validating that sync rules can be called async and worked the same way, and async rules can't be called sync, throwing exception

2024-06-05 05:15 UTC, rockfordlhotka requested changes
We need to add an `AuthorizationRuleAsync` class to provide basic implementation of the `IAuthorizationRuleAsync` interface - like the existing `AuthorizationRule` class.

2024-06-05 05:15 UTC, rockfordlhotka commented on Source/Csla/Rules/IAuthorizationRuleBase.cs
> +  public interface IAuthorizationRule : IAuthorizationRuleBase
This interface should be in its own file

2024-06-05 05:15 UTC, rockfordlhotka commented on Source/Csla/Rules/IAuthorizationRuleBase.cs
> +  public interface IAuthorizationRuleAsync : IAuthorizationRuleBase
This interface also should be in its own file

2024-06-06 18:52 UTC, rockfordlhotka approved these changes

2024-06-06 18:53 UTC, merged