Provide images for documentation about Roslyn Analyzers
MarimerLLC/csla pull request #4063
Opened 2024-06-25 06:25 UTC by kant2002

Also
- Add fix for the code fix broken when static constructor is present in the class.
- Add debugging setup for the Csla.Analyzers project

Closes #1519
Closes #4061

2024-06-25 06:27 UTC, kant2002 commented on Source/Csla.Analyzers/Csla.Analyzers/Properties/launchSettings.json
> +      "commandName": "DebugRoslynComponent"
that's allow debug of Analyzers, but not codeFix, you should add Analyzer project locally, but that at least half the way to do that nicely.

2024-06-26 00:16 UTC, rockfordlhotka requested changes

2024-06-26 00:16 UTC, rockfordlhotka commented on docs/Analyzers.md
>  If you have an idea for an analyzer that would be beneficial for developers using CSLA, please propose it in the forums (https://github.com/MarimerLLC/cslaforum/issues). Tag it with "feature discussi
The current/correct url is https://github.com/MarimerLLC/csla/discussions

2024-06-26 00:16 UTC, rockfordlhotka commented on Source/Csla.Analyzers/Csla.Analyzers/CheckConstructorsAnalyzerPublicConstructorCodeFix.cs
> +      //System.Diagnostics.Debugger.Launch();
Remove commented code

2024-06-26 03:47 UTC, rockfordlhotka approved these changes

2024-06-26 03:48 UTC, merged