Features/source generator autoimplement
MarimerLLC/csla pull request #4124
Opened 2024-07-28 23:27 UTC by luizfbicalho

Closes #4098

2024-07-30 20:08 UTC, StefanOssendorf commented
I have only skimmed over some files. But there seem to be a lot of xml-comment c&p errors. Especially on classes which are used by users. Please double check that.

2024-07-30 21:10 UTC, luizfbicalho commented
> I have only skimmed over some files. But there seem to be a lot of xml-comment c&p errors. Especially on classes which are used by users. Please double check that.

Sorry about that , I had it on my list and checked it as done wrongly, I'll do that later

2024-07-30 22:14 UTC, luizfbicalho commented
> I have only skimmed over some files. But there seem to be a lot of xml-comment c&p errors. Especially on classes which are used by users. Please double check that.

I changed the comments, do you think that we should change the namespace of the attribute? or some other namespaces?

2024-07-31 18:44 UTC, rockfordlhotka requested changes

2024-07-31 18:44 UTC, rockfordlhotka commented on Source/Csla.Generators/cs/AutoImplementProperties/readme.md
Is this file accurate for the latest AutoImplementProperties behaviors?

2024-07-31 18:44 UTC, rockfordlhotka commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
We can't use the built-in hashcode capabilities of .NET?

Also, just to confirm, this is original code, and not something brought in from another source?

2024-07-31 18:44 UTC, rockfordlhotka commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
> +﻿using System.ComponentModel;
Missing standard file header/copyright

2024-07-31 18:44 UTC, rockfordlhotka commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/AutoImplement/Discovery/DefinitionExtractionContext.cs
A general question I have with all the support classes that abstract Roslyn: should these be part of this specific generator, or are they useful for _any_ generator and should be their own project/dll that can be reused in the future?

2024-07-31 19:17 UTC, luizfbicalho commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
This is a gift from @StefanOssendorf

2024-07-31 19:21 UTC, luizfbicalho commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/AutoImplement/Discovery/DefinitionExtractionContext.cs
I think that this is very specific, I copied from the other generator but it's like a linq query over a database, it's the view model that I need here.
surely they are similar but they should evolve not in the same direction

2024-07-31 19:21 UTC, rockfordlhotka commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
I'm fine with it as long as the IP is clearly available for use in CSLA. Can you confirm that @StefanOssendorf ?

2024-07-31 23:11 UTC, luizfbicalho commented on Source/Csla.Generators/cs/AutoImplementProperties/readme.md
This I forgot, sending now

2024-07-31 23:18 UTC, luizfbicalho commented
> > > I have only skimmed over some files. But there seem to be a lot of xml-comment c&p errors. Especially on classes which are used by users. Please double check that.
> > 
> > 
> > I changed the comments, do you think that we should change the namespace of the attribute? or some other namespaces?
> 
> I think the attributes should probably be in the `Csla` namespace so they are available by default if someone has added the generator package to their project.

Changed to Csla

2024-08-01 05:20 UTC, ossendorf-at-hoelscher commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
I don't think it's my IP I guess?
I took it from here (there's also a comment in my gen that it's taken from there) https://github.com/andrewlock/StronglyTypedId/blob/master/src/StronglyTypedIds/HashCode.cs based/recommended from the author here https://andrewlock.net/creating-a-source-generator-part-9-avoiding-performance-pitfalls-in-incremental-generators/#4-watch-out-for-collection-types

2024-08-01 05:22 UTC, ossendorf-at-hoelscher commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
In that regard maybe we should consider https://www.nuget.org/packages/Microsoft.Bcl.HashCode/ as a substitute?

2024-08-02 04:06 UTC, rockfordlhotka commented on Source/Csla.Generators/cs/AutoImplementProperties/Csla.Generator.AutoImplementProperties.CSharp/Internals/HashCode.cs
I think that is best, please make that change @luizfbicalho.

2024-08-03 23:29 UTC, luizfbicalho commented
Updated

2024-08-06 18:13 UTC, rockfordlhotka approved these changes

2024-08-06 18:14 UTC, merged