Features/add nonserialized backing fields
MarimerLLC/csla pull request #4197
Opened 2024-09-01 19:52 UTC by luizfbicalho

Closes: #1628

2024-09-02 19:22 UTC, StefanOssendorf commented
Sorry I'm late to the party. I've asked a question in the related issue.

2024-09-03 21:26 UTC, rockfordlhotka requested changes

2024-09-03 21:26 UTC, rockfordlhotka commented on Source/Csla/Core/FieldManager/FieldData.cs
> +    public bool IsSerializable { get; set; }
Shouldn't this be readonly?

2024-09-03 21:26 UTC, rockfordlhotka commented on Source/Csla/Core/FieldManager/FieldDataManager.cs
> +      return [.. _propertyList];
Why the added space?

2024-09-03 21:30 UTC, luizfbicalho commented on Source/Csla/Core/FieldManager/FieldDataManager.cs
> +      return [.. _propertyList];
was added by the code cleanup

2024-09-03 21:34 UTC, luizfbicalho commented on Source/Csla/Core/FieldManager/FieldData.cs
> +    public bool IsSerializable { get; set; }
added a private set

2024-09-03 21:37 UTC, rockfordlhotka approved these changes

2024-09-03 22:35 UTC, merged